#!/usr/bin/python
import os
import argparse
from lib.compiler import *

if __name__ == "__main__":
    argparser = argparse.ArgumentParser('Quick-Bash Compiler')
    g = argparser.add_mutually_exclusive_group(required=True)
    g.add_argument('-c', '--command', help='Evaluate the passed string')
    g.add_argument('-f', '--file', help='Compile the specified source file')
    parameters = argparser.parse_args()

    if g.command is None:
        print qsh_file(parameters.file)
    else:
        print qsh(parameters.command)


