# List of token names.   This is always required
tokens = (
 'INTEGER',
 'DECIMAL',
 'PLUS',
 'MINUS',
 'TIMES',
 'DIVIDE',
 'LPAREN',
 'RPAREN',
 'LBRACE',
 'RBRACE',
 'EQUALS',
 'SEMICOLON',
 'LGEQUALS',
 'VARIABLE',
 'GT',
 'LT',
 'LE',
 'GE',
 'CODEBLOCK',
 'SINGLE_QUOTE',
 'DOUBLE_QUOTE',
 'BUILTIN_FUNCTION',
 'RESERVED',
 'UTILITY',
 'COMMA',
 'KEYWORDS',
 'STRING',
 'TO',
 'PIPE',
 'APPEND'
)

logical = [
  'IF', 'ELSEIF', 'ELSE'
]

reserved = {
   'if'       : 'IF',
   'then'     : 'THEN',
   'else'     : 'ELSE',
   'elseif'   : 'ELSEIF',
   'while'    : 'WHILE',
   'for'      : 'FOR',
   'in'       : 'IN',
   'function' : 'FUNCTION',
   'return'   : 'RETURN',
   'not'      : 'NOT',
   'and'      : 'AND',
   'or'       : 'OR'
}

builtin_functions = {
   'print' : 'PRINT',
   'echo'  : 'ECHO'
}

utilities = [
      'bash',
      'bunzip2',
      'bzcat',
      'bzcmp',
      'bzdiff',
      'bzegrep',
      'bzexe',
      'bzfgrep',
      'bzgrep',
      'bzip2',
      'bzip2recover',
      'bzless',
      'bzmore',
      'cat',
      'chgrp',
      'chmod',
      'chown',
      'chvt',
      'cp',
      'dash',
      'date',
      'dd',
      'df',
      'dir',
      'dmesg',
      'echo',
      'ed',
      'egrep',
      'false',
      'fgrep',
      'fuser',
      'fusermount',
      'grep',
      'gunzip',
      'gzexe',
      'gzip',
      'hostname',
      'kill',
      'less',
      'lessecho',
      'lessfile',
      'lesskey',
      'lesspipe',
      'ln',
      'loadkeys',
      'login',
      'ls',
      'lsmod',
      'mkdir',
      'mknod',
      'mktemp',
      'more',
      'mount',
      'mountpoint',
      'mt',
      'mv',
      'nano',
      'nc',
      'netcat',
      'netstat',
      'nisdomainname',
      'open',
      'openvt',
      'pidof',
      'ping',
      'ping6',
      'plymouth',
      'ps',
      'pwd',
      'rbash',
      'readlink',
      'rm',
      'rmdir',
      'rnano',
      'sed',
      'setfont',
      'setupcon',
      'sh',
      'sleep',
      'stty',
      'su',
      'sync',
      'tailf',
      'tar',
      'tempfile',
      'touch',
      'true',
      'umount',
      'uname',
      'uncompress',
      'vdir',
      'which',
      'zcat',
      'zcmp',
      'zdiff',
      'zegrep',
      'zfgrep',
      'zforce',
      'zgrep',
      'zless',
      'zmore',
      'znew'
]
